honestica/docker-looker

- Dockerfile
- README.md
Mise à jour du readme + update à la dernière version
Release note à lire avant de déployer
> Mise à jour du readme + update à la dernière version

- Dockerfile
Upgrades looker.
https://honestica.atlassian.net/browse/INFRAOPS-1454 - `MAJ Looker -> 21.0`
> [looker] Upgrade

- Dockerfile
- jmx_prometheus_javaagent.yaml
Ajout de l'agent jmx pour prometheus.
> Add JMX prometheus exporter

- Dockerfile
> [looker] Upgrade to last version

- Dockerfile
Current version is full of critical CVEs.
> Update jmx exporter

- .circleci/config.yml
- Dockerfile
- Fix docker version for image build and push
- Also fix looker version, between my PR and merge the version changed
https://honestica.atlassian.net/browse/INFRAOPS-2400 - `MAJ Looker `
> Fix ci build master

- Dockerfile
- Makefile
- chromium
- spec/dockerfile_spec.rb
- spec/page.html
Looker fails at rendering PDF:
Here are server logs:
```
Chrome process init failure; may retry. Error: Couldn't start Chromium: Could not connect to devtools after 30555 ms.
Chromium Renderer called with options: {\"login\":{\"type\":\"EPHEMERAL\",\"url\":\"/login/ephemeral\",\"token\":\"ZjS5W2ZmVjgdnBVckpBydCHPMFZyWJJs5MDnTxyMnwXPmZmSTxPcYJKrVWJ6Hwv4\"},\"timeouts\":{\"total\":1800000,\"login\":300000,\"poll\":1000,\"tileQuiesce\":60000,\"dashboardQuiesce\":2000},\"target\":{\"url\":\"/dashboards/2\",\"presentationUrl\":\"/dashboards/2?print_mode=true&run=1&layout=print\",\"type\":\"DASHBOARD_NEXT\",\"id\":\"2\",\"params\":\"\",\"context\":\"download\",\"assets\":[]},\"output\":{\"requestedDimensions\":{\"width\":1680,\"height\":1},\"computedDimensions\":{\"width\":1680,\"height\":-1},\" …
```
> [bug] Try fixing chrome pdf rendering

- Dockerfile
- spec/dockerfile_spec.rb
An other try to fix rendering issue:
The previous upgrade did not fixed the issue.
Error log:
[looker_chromium_error.csv](https://github.com/honestica/docker-looker/files/9150842/looker_chromium_error.csv)
This PR:
- adds tests
- upgrades looker to last release
- downgrade chrome to the current production version (that seems to work)
https://honestica.atlassian.net/browse/INFRAOPS-2560 - `Installation Chromium Looker Embed`
> [deps] Try fixing chrome rendering issue

- Dockerfile
The version changed between my PR and the merge.
> [dep] Upgrade looker to available version

- Dockerfile
> Upgrade Looker to 22.20

- .circleci/config.yml
- Dockerfile
- Makefile
- scripts/common.rb
- scripts/download
- scripts/full_version
Corrige l'erreur:
```
{"error":"Invalid Request"}curl: (6) Could not resolve host: null
The command '/bin/sh -c curl -Ss -X POST -H 'Content-Type: application/json' -d '{"lic": "'"$LICENSE"'", "email": "'"$EMAIL"'", "latest": "specific", "specific": "looker-'"$LOOKER_VERSION"'.jar"}' https://apidownload.looker.com/download > api_response.json   && cat api_response.json && curl -Ss "$(cat api_response.json | jq -r '.url')" -o $LOOKER_DIR/looker.jar   && curl -Ss "$(cat api_response.json | jq -r '.depUrl')" -o $LOOKER_DIR/looker-dependencies.jar' returned a non-zero code: 6
make: *** [Makefile:18: build] Error 6
```
Looker ne garde que la dernière `patch` pour chaque version `mineure`.
https://honestica.atlassian.net/browse/INFRAOPS-3886 - `[docker-looker] Meilleure gestion des versions`
> Fix version download

- .circleci/config.yml
> feat(INFRAOPS-4217): build the looker 23.2 image

- Dockerfile
Met à jour chrome afin de tenter de résoudre les soucis de rendering des cartes en PDF.
https://community.looker.com/general-looker-administration-35/troubleshooting-common-chromium-errors-20621?postid=61349#post61349
> [deps] Upgrade chrome

- Dockerfile
- Makefile
- chromium
- spec/dockerfile_spec.rb
Fix chrome execution due to home point to `/opt/looker` while this path is read only in production.
> [chrome] Fix homedir so chrome start correctly

- Dockerfile
- spec/dockerfile_spec.rb
Essai de la dernière version de chrome, la version 109 ne semble pas fonctionner correctement avec looker.
> [chrome] Upgrade to last version to try fixing rendering not working

- Dockerfile
- chromium
- spec/dockerfile_spec.rb
Passage à chromium au lieu de google-chrome.
> [dep] Switch from chrome to chromium

- chromium
Try to solve:
```
[0412/110532.713189:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```
> [chromium] Fix DBUS address

- Dockerfile
- spec/dockerfile_spec.rb
Rollback chrome to version 99.
> [chrome] Rollback to last 99 version

- spec/dockerfile_spec.rb
Ajouts de tests supplémentaires à chrome.
J'ai dans l'espoir d'en ajouter encore d'autres suivant le retour de looker.
Le but étant de réussir à attraper le soucis lié aux dernières versions (que je n'arrive pas à avoir dans les tests, sous-entendu je ne sais pas ce qui ne fonctionne pas) pour un jour pouvoir upgrade chrome sans risque :trollface: .
> [chrome] Write more tests

- .circleci/config.yml
Upgrade de looker à la 23.4.
https://cloud.google.com/looker/docs/looker-23-changelog?hl=fr#234
> [looker] Upgrade to 23.4

- .circleci/config.yml
> [looker] Upgrade to 23.6

- .circleci/config.yml
- Dockerfile
- spec/dockerfile_spec.rb
Upgrade de:
- looker version 23.10
- chrome version 113 
https://honestica.atlassian.net/browse/INFRAOPS-4708 - `[looker] Upgrade to 23.10 and chrome 113`
> Upgrade looker and chrome version

- .circleci/config.yml
- Dockerfile
- spec/dockerfile_spec.rb
Upgrade vers la 23.20.
https://honestica.atlassian.net/browse/INFRAOPS-5383 - `[looker] Upgrade to 23.20`
> [looker] Upgrade to 23.20

- .circleci/config.yml
Le projet ne peut pas build avec la version 20 de docker.
> [CI] Fix docker version

- .circleci/config.yml
- Dockerfile
Give some context to help the review :).
Some link that could help.
> bump JMX exporter version + looker `24.2` -> `24.12`

- .circleci/config.yml
https://honestica.atlassian.net/browse/INFRAOPS-6513
> upgrade looker to v24.14

- .circleci/config.yml
Give some context to help the review :).
Some link that could help.
> upgrade looker to v24.16

- spec/dockerfile_spec.rb
Ajoute un test pour détecter le jour où on peut réactiver l'exporteur.
```java
uri:classloader:/helltool/lib/helltool/configuration/initializer.class:7: warning: The Psych YAML extension failed to load.
Check your env for conflicting versions of SnakeYAML
See https://github.com/jruby/jruby/wiki/FAQs#why-does-the-psych-yaml-extension-fail-to-load-in-my-environment
ERROR: org.jruby.embed.EvalFailedException: (LoadError) bad SnakeYAML version 2.2, required 1.21 or higher; check your CLASSPATH for a conflicting jar
```
Cf.:
- https://github.com/lifen-infrastructure/k8s/pull/4612 
- https://honestica.atlassian.net/browse/INFRAOPS-6513
> [spec] Add a test for temporary removed JMX exporter from production due to SnakeYAML conflict

- .circleci/config.yml
- Dockerfile
- spec/dockerfile_spec.rb
Asked by @eTitiB 
https://honestica.atlassian.net/browse/INFRAOPS-6800
> Infraops 6800 upgrade looker v25 0

- .circleci/config.yml
Give some context to help the review :).
Some link that could help.
> Chore: Add Semgrep CircleCI config

- docker/Dockerfile
- spec/dockerfile_spec.rb
Mise à jour manuelle de maven pour corriger la CVE.
> Manage maven so we fix CVE
